kind: pipeline
name: default

workspace:
  path: /source

volumes:
  - name: pnpm-cache
    host:
      path: /root/.pnpm-cache

trigger:
  ref:
    - refs/heads/**

steps:
  - name: install
    image: node:20.13.0
    volumes:
      - name: pnpm-cache
        path: /source/.pnpm-store
    commands:
      - npm i -g pnpm
      - pnpm i
    environment:
      HUSKY: 0

  - name: check
    image: node:20.13.0
    commands:
      - npm run format
      - npm run lint
      - npm run check-types

  - name: test
    image: node:20.13.0
    commands:
      - npm run test

  - name: auth
    image: robertstettner/drone-npm-auth
    settings:
      token:
        from_secret: NPM_TOKEN
    when:
      branch:
        - main

  - name: publish
    image: node:20.13.0
    commands:
      - npm run publish
    when:
      branch:
        - main
