kind: pipeline
name: check-and-test
type: docker

workspace:
  path: /source

volumes:
  - name: pnpm-cache
    host:
      path: /root/.pnpm-cache

trigger:
  ref:
    - refs/heads/**

steps:
  - name: install
    image: node:20.13.0
    volumes:
      - name: pnpm-cache
        path: /source/.pnpm-store
    commands:
      - npm i -g pnpm
      - pnpm i
    environment:
      HUSKY: 0

  - name: check
    image: node:20.13.0
    commands:
      - npm run format
      - npm run lint
      - npm run check-types

  - name: test
    image: node:20.13.0
    commands:
      - npm run test

---
kind: pipeline
name: publish
type: docker

workspace:
  path: /source

volumes:
  - name: pnpm-cache
    host:
      path: /root/.pnpm-cache

trigger:
  ref:
    - refs/heads/main
    - refs/tags/*

steps:
  - name: install
    image: node:20.13.0
    volumes:
      - name: pnpm-cache
        path: /source/.pnpm-store
    commands:
      - npm i -g pnpm
      - pnpm i
    environment:
      HUSKY: 0
    when:
      event:
        - tag

  - name: build
    image: node:20.13.0
    commands:
      - npm run build
    when:
      event:
        - tag

  - name: auth
    image: robertstettner/drone-npm-auth
    settings:
      token:
        from_secret: NPM_TOKEN
    when:
      event:
        - tag

  - name: publish
    image: node:20.13.0
    commands:
      - npm publish
    when:
      event:
        - tag
