name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.13.0

      - name: Install
        run: pnpm i

      - name: Format
        run: pnpm format

      - name: Format
        run: pnpm lint

      - name: Format
        run: pnpm check-types

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16,18,20,22]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: pnpm i

      - name: Test
        run: pnpm test
